export const UNPRESERVE_FORMBUILDER_STATE = "UNPRESERVE_FORMBUILDER_STATE";

export const PRESERVE_FORMBUILDER_STATE = "PRESERVE_FORMBUILDER_STATE";
export const SAVE_PROCESSED_RESPONSES = "SAVE_PROCESSED_RESPONSES";
export const DELETE_BUSINESS_ACCOUNT = "DELETE_BUSINESS_ACCOUNT";
export const DELETE_BUSINESS_BRANCH = "DELETE_BUSINESS_BRANCH";
export const UPDATE_UPLOAD_STATUS = "UPDATE_UPLOAD_STATUS";

export const SAVE_PENDING_RESPONSES = "SAVE_PENDING_PRESPONSE";
export const START_NETWORK_REQUEST = "START_NETWORK_REQUEST";
export const NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE";
export const UNPRESERVE_NEW_FORM = "UNPRESERVE_NEW_FORM";

export const HOLD_UPLOADED_FILE_URL = "HOLD_UPLOADED_FILE_URL";
export const DROP_UPLOADED_FILE_URL = "DROP_UPLOADED_FILE_URL";

export const UPDATE_RESPONSE_NOTE = "UPDATE_RESPONSE_NOTE";
export const STOP_NETWORK_REQUEST = "END_NETWORK_REQUEST";
export const REMOVE_FORM_ELEMENT = "REMOVE_FORM_ELEMENT";
export const PRESERVE_NEW_FORM = "PRESERVE_NEW_FORM";

export const END_NOTIFICATION = "END_NOTIFICATION";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const SAVE_WORKSPACES = "SAVE_WORKSPACES";

export const START_NEW_FORM = "START_NEW_FORM";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const UPDATE_FORMS = "UPDATE_FORMS";

export const STORE_BUSINESS = "STORE_BUSINESS";
export const SAVE_FORMS = "SAVE_FORMS";
export const STORE_USER = "STORE_USER";

export const SAVE_PARTIALLYPROCESSED_RESPONSES =
  "SAVE_PARTIALLYPROCESSED_RESPONSES";
