export const SAVE_PROCESSED_RESPONSES = "SAVE_PROCESSED_RESPONSES";
export const SAVE_PENDING_RESPONSES = "SAVE_PENDING_PRESPONSE";
export const START_NETWORK_REQUEST = "START_NETWORK_REQUEST";
export const UNPRESERVE_FOR_PREVIEW = "UNPRESERVE_NEW_FORM";
export const SAVE_NOTED_RESPONSES = "SAVE_NOTED_RESPONSES";

export const NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE";
export const PRESERVE_FOR_PREVIEW = "PRESERVE_FOR_PREVIEW";
export const STOP_NETWORK_REQUEST = "END_NETWORK_REQUEST";
export const REMOVE_FORM_ELEMENT = "REMOVE_FORM_ELEMENT";

export const END_NOTIFICATION = "END_NOTIFICATION";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const SAVE_WORKSPACES = "SAVE_WORKSPACES";

export const START_NEW_FORM = "START_NEW_FORM";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const UPDATE_FORMS = "UPDATE_FORMS";
export const DELETE_USER = "DELETE_USER";

export const SAVE_FORMS = "SAVE_FORMS";
export const SAVE_STATS = "SAVE_STATS";
export const SAVE_USER = "SAVE_USER";
